### ISSUE TITLE
Possible Path, with backslashes, is not valid

### ISSUE THREAD

**Issue by DanielSiepmann** [martin-helmich/typo3-typoscript-parser#1]
TypoScript allows usages of backslashes inside assignments (to allow configuration of classes).
The following is valid TypoScript, but can't be parsed:
```
config.tx_extbase {
    view {
        # Configure where to look for widget templates
        widget {
            TYPO3\CMS\Fluid\ViewHelpers\Widget\PaginateViewHelper {
                templateRootPath = EXT:ext_key/Resources/Private/Templates
            }
        }
    }
}
```
But we receive the following error for the line:
`Tokenization error: Cannot tokenize line "TYPO3\CMS\Fluid\ViewHelpers\Widget\PaginateViewHelper {"`

**Comment by martin-helmich** [comment]
Thanks for the report. I'll see if I can whip up a test case for this issue.
