### ISSUE TITLE
Overwriting path in backend modules via TSconfig leads to an error

### ISSUE THREAD

**Issue by einpraegsam** [martin-helmich/typo3-typoscript-parser#111]
If you overrule a backend module path via TSConfig like
`templates.in2code/luxletter.1732878717 = in2code/lux:/Resources/Private/`

an error occured like:
```
Completed with 1 issues
CHECKSTYLE REPORT
=> /github/workspace/Configuration/TSConfig/Lux.typoscript.
 42 Tokenization error: Cannot tokenize line "templates.in2code/luxletter.1732878717 = in2code/lux:/Resources/Private/"
SUMMARY
1 issues in total. (1 errors)
```

But the typoscript is correct and follows the rules:
https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/PageTsconfig/Templates.html

**Comment by martin-helmich** [comment]
@einpraegsam I tried adding a failing test case for this issue, but haven't been lucky so far -- the example you've provided seems to make it through the parser fine. Can you check the versions of `helmich/typo3-typoscript-lint` and `helmich/typo3-typoscript-parser` that you're using?

**Comment by einpraegsam** [comment]
I'm using version 3.2.1 in the project: https://github.com/in2code-de/lux/blob/develop/composer.json#L69

I separated the file https://github.com/in2code-de/lux/blob/develop/Configuration/TSConfig/LuxLetter.typoscript to the exclude list, to make github actions happy

**Comment by einpraegsam** [comment]
Okay, thx for looking into it
