### ISSUE TITLE
Tokenization error with colon in keys

### ISSUE THREAD

**Issue by mbrodala** [martin-helmich/typo3-typoscript-parser#14]
The following TypoScript:

```
page {
  meta {
    foo:bar.cObject = TEXT
    foo:bar.cObject.value = qux
  }
}
```

Yields the following warning with  [typo3-typoscript-lint](https://github.com/martin-helmich/typo3-typoscript-lint/):

```
Linting input file .../test.ts.

CHECKSTYLE REPORT
=> .../test.ts.
   3 Tokenization error: Cannot tokenize line "foo:bar.cObject = TEXT"

SUMMARY
1 warnings in total.
```

However, the TYPO3 TypoScript parser is fine with this and in the end a valid `<meta>` element is outputted.

**Comment by martin-helmich** [comment]
Thanks for the report, this behaviour is definitely not intentional. Will take a look as soon as I get the chance.

**Comment by mbrodala** [comment]
Thanks for fixing. :-)
