### ISSUE TITLE
False positive on comment after delete operator

### ISSUE THREAD

**Issue by martin-helmich** [martin-helmich/typo3-typoscript-parser#22]
Migrated from martin-helmich/typo3-typoscript-lint#33 (originally by @mbrodala):

>Given the following TypoScript:
>
>```
>foo > # Something
>```
>
>The linter shows the following error:
>
>> Parse error: Unexpected token RVALUE after delete operator (expected line break).
>
>However, comments after the delete operator (although unusual) are perfectly fine.

**Comment by martin-helmich** [comment]
Actually, [the docs](https://docs.typo3.org/typo3cms/TyposcriptSyntaxReference/Syntax/TypoScriptSyntax/Index.html#comments) are quite clear on this:

>When a line starts with `//` or `#` it is considered to be a comment and will be ignored.

So according to the spec, a comment starting at the end of a line *should* be invalid, meaning the parse error is technically correct. However, since TYPO3 obviously parses this successfully, this library should as well.

**Comment by mbrodala** [comment]
Thanks. :-)
