### ISSUE TITLE
Tokenization errors thrown on INCLUDE_TYPOSCRIPT lines

### ISSUE THREAD

**Issue by julian-mair** [martin-helmich/typo3-typoscript-parser#30]
**Output:**
```
CHECKSTYLE REPORT
=> C:\Users\Julian Mair\_work\development\test\Configuration\TypoScript\constants.typoscript.
  25 Tokenization error: Cannot tokenize line "<INCLUDE_TYPOSCRIPT:source="FILE:EXT:test/Configuration/TypoScript/Constants/Language/_general.typoscript">"
[...]
```
**Fix:**

On line [39](https://github.com/martin-helmich/typo3-typoscript-parser/blob/master/src/Helmich/TypoScriptParser/Tokenizer/Tokenizer.php#L39) of Tokenizer.php the `+` sign should be a `*`, because for includes a whitespace is not mandatory.

**Comment by martin-helmich** [comment]
You're absolutely right, thanks for reporting this :+1:. Fix incoming.
