### ISSUE TITLE
false positive: Parse error: unknown attribute 'extension' found in INCLUDE statement

### ISSUE THREAD

**Issue by fgerards** [martin-helmich/typo3-typoscript-parser#36]
the INCLUDE_TYPOSCRIPT statement has valid attribute "extension" to define the file extension taken into account when using the DIR: syntax inside the source-Attribute.
PLz fix.

**Comment by martin-helmich** [comment]
That's because, [according to the docs](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/TypoScriptSyntax/Syntax/Includes.html#alternative-traditional-syntax), it's `extensions`, and not `extension`.
