### ISSUE TITLE
Lost indent after typoscript change / Execution via rector

### ISSUE THREAD

**Issue by ayacoo** [martin-helmich/typo3-typoscript-parser#67]
Here is a copy of an issue from TYPO3 Rector: [Lost indent after typoscript change](https://github.com/sabbelasichon/typo3-rector/issues/2458)

**Example code**
```
[applicationContext = "Development*"]
    config.tx_realurl_enable = 0
[global]
```

**Result**
```
[applicationContext == "Development*"]
config.tx_realurl_enable = 0
[global]
```

**Expected result**
```
[applicationContext == "Development*"]
    config.tx_realurl_enable = 0
[global]
```

**Feedback from Sebastian:**

"I have checked it and it must be an issue in the parser itself. Have a look at these two files:

https://github.com/martin-helmich/typo3-typoscript-parser/blob/master/tests/functional/Parser/Fixtures/Assignments/comment_multiline.typoscript

https://github.com/martin-helmich/typo3-typoscript-parser/blob/master/tests/functional/Parser/Fixtures/Assignments/comment_multiline.typoscript.print

The first one is the input and the second one the output. The trailing whitespaces are lost here while writing back to file."

**Comment by martin-helmich** [comment]
Not sure if this is still current. Anyway, there've been earlier discussions on how much formatting information from the input code the parser should actually preserve. Right now, the `PrettyPrinter` class has absolute control over how printed code is formatted. For convenience, #80 now adds a configuration flag with which indentation in condition can be configured globally.
