### ISSUE TITLE
prettyPrinter indention 4 space vs. 2 space

### ISSUE THREAD

**Issue by juergen-venne** [martin-helmich/typo3-typoscript-parser#81]
Your parser indents TypoScript using 4 spaces.
The TYPO3 core .editorconfig file indeed says 2 spaces.
https://github.com/TYPO3/typo3/blob/main/.editorconfig#L47

Who's right? :-)

I use TYPO3 rector to update my TypoScript code. The two different settings make it difficult to keep my code clean.
However I'm totally fine with 4 and also with 2 spaces. But it would be great if the setting would be synchronised with the core setting.

**Comment by sabbelasichon** [comment]
@juergen-venne This will be now configurable in TYPO3-Rector itself. https://github.com/sabbelasichon/typo3-rector/pull/3208
Has nothing to do with this package. So i am going to close this issue here.
